(ns rn-styles.colors)

(def aliceblue "aliceblue") ;; #f0f8ff
(def antiquewhite "antiquewhite") ;; #faebd7
(def aqua "aqua") ;; #00ffff
(def aquamarine "aquamarine") ;; #7fffd4
(def azure "azure") ;; #f0ffff
(def beige "beige") ;; #f5f5dc
(def bisque "bisque") ;; #ffe4c4
(def black "black") ;; #000000
(def blanchedalmond "blanchedalmond") ;; #ffebcd
(def blue "blue") ;; #0000ff
(def blueviolet "blueviolet") ;; #8a2be2
(def brown "brown") ;; #a52a2a
(def burlywood "burlywood") ;; #deb887
(def cadetblue "cadetblue") ;; #5f9ea0
(def chartreuse "chartreuse") ;; #7fff00
(def chocolate "chocolate") ;; #d2691e
(def coral "coral") ;; #ff7f50
(def cornflowerblue "cornflowerblue") ;; #6495ed
(def cornsilk "cornsilk") ;; #fff8dc
(def crimson "crimson") ;; #dc143c
(def cyan "cyan") ;; #00ffff
(def darkblue "darkblue") ;; #00008b
(def darkcyan "darkcyan") ;; #008b8b
(def darkgoldenrod "darkgoldenrod") ;; #b8860b
(def darkgray "darkgray") ;; #a9a9a9
(def darkgreen "darkgreen") ;; #006400
(def darkgrey "darkgrey") ;; #a9a9a9
(def darkkhaki "darkkhaki") ;; #bdb76b
(def darkmagenta "darkmagenta") ;; #8b008b
(def darkolivegreen "darkolivegreen") ;; #556b2f
(def darkorange "darkorange") ;; #ff8c00
(def darkorchid "darkorchid") ;; #9932cc
(def darkred "darkred") ;; #8b0000
(def darksalmon "darksalmon") ;; #e9967a
(def darkseagreen "darkseagreen") ;; #8fbc8f
(def darkslateblue "darkslateblue") ;; #483d8b
(def darkslategrey "darkslategrey") ;; #2f4f4f
(def darkturquoise "darkturquoise") ;; #00ced1
(def darkviolet "darkviolet") ;; #9400d3
(def deeppink "deeppink") ;; #ff1493
(def deepskyblue "deepskyblue") ;; #00bfff
(def dimgray "dimgray") ;; #696969
(def dimgrey "dimgrey") ;; #696969
(def dodgerblue "dodgerblue") ;; #1e90ff
(def firebrick "firebrick") ;; #b22222
(def floralwhite "floralwhite") ;; #fffaf0
(def forestgreen "forestgreen") ;; #228b22
(def fuchsia "fuchsia") ;; #ff00ff
(def gainsboro "gainsboro") ;; #dcdcdc
(def ghostwhite "ghostwhite") ;; #f8f8ff
(def gold "gold") ;; #ffd700
(def goldenrod "goldenrod") ;; #daa520
(def gray "gray") ;; #808080
(def green "green") ;; #008000
(def greenyellow "greenyellow") ;; #adff2f
(def grey "grey") ;; #808080
(def honeydew "honeydew") ;; #f0fff0
(def hotpink "hotpink") ;; #ff69b4
(def indianred "indianred") ;; #cd5c5c
(def indigo "indigo") ;; #4b0082
(def ivory "ivory") ;; #fffff0
(def khaki "khaki") ;; #f0e68c
(def lavender "lavender") ;; #e6e6fa
(def lavenderblush "lavenderblush") ;; #fff0f5
(def lawngreen "lawngreen") ;; #7cfc00
(def lemonchiffon "lemonchiffon") ;; #fffacd
(def lightblue "lightblue") ;; #add8e6
(def lightcoral "lightcoral") ;; #f08080
(def lightcyan "lightcyan") ;; #e0ffff
(def lightgoldenrodyellow "lightgoldenrodyellow") ;; #fafad2
(def lightgray "lightgray") ;; #d3d3d3
(def lightgreen "lightgreen") ;; #90ee90
(def lightgrey "lightgrey") ;; #d3d3d3
(def lightpink "lightpink") ;; #ffb6c1
(def lightsalmon "lightsalmon") ;; #ffa07a
(def lightseagreen "lightseagreen") ;; #20b2aa
(def lightskyblue "lightskyblue") ;; #87cefa
(def lightslategrey "lightslategrey") ;; #778899
(def lightsteelblue "lightsteelblue") ;; #b0c4de
(def lightyellow "lightyellow") ;; #ffffe0
(def lime "lime") ;; #00ff00
(def limegreen "limegreen") ;; #32cd32
(def linen "linen") ;; #faf0e6
(def magenta "magenta") ;; #ff00ff
(def maroon "maroon") ;; #800000
(def mediumaquamarine "mediumaquamarine") ;; #66cdaa
(def mediumblue "mediumblue") ;; #0000cd
(def mediumorchid "mediumorchid") ;; #ba55d3
(def mediumpurple "mediumpurple") ;; #9370db
(def mediumseagreen "mediumseagreen") ;; #3cb371
(def mediumslateblue "mediumslateblue") ;; #7b68ee
(def mediumspringgreen "mediumspringgreen") ;; #00fa9a
(def mediumturquoise "mediumturquoise") ;; #48d1cc
(def mediumvioletred "mediumvioletred") ;; #c71585
(def midnightblue "midnightblue") ;; #191970
(def mintcream "mintcream") ;; #f5fffa
(def mistyrose "mistyrose") ;; #ffe4e1
(def moccasin "moccasin") ;; #ffe4b5
(def navajowhite "navajowhite") ;; #ffdead
(def navy "navy") ;; #000080
(def oldlace "oldlace") ;; #fdf5e6
(def olive "olive") ;; #808000
(def olivedrab "olivedrab") ;; #6b8e23
(def orange "orange") ;; #ffa500
(def orangered "orangered") ;; #ff4500
(def orchid "orchid") ;; #da70d6
(def palegoldenrod "palegoldenrod") ;; #eee8aa
(def palegreen "palegreen") ;; #98fb98
(def paleturquoise "paleturquoise") ;; #afeeee
(def palevioletred "palevioletred") ;; #db7093
(def papayawhip "papayawhip") ;; #ffefd5
(def peachpuff "peachpuff") ;; #ffdab9
(def peru "peru") ;; #cd853f
(def pink "pink") ;; #ffc0cb
(def plum "plum") ;; #dda0dd
(def powderblue "powderblue") ;; #b0e0e6
(def purple "purple") ;; #800080
(def rebeccapurple "rebeccapurple") ;; #663399
(def red "red") ;; #ff0000
(def rosybrown "rosybrown") ;; #bc8f8f
(def royalblue "royalblue") ;; #4169e1
(def saddlebrown "saddlebrown") ;; #8b4513
(def salmon "salmon") ;; #fa8072
(def sandybrown "sandybrown") ;; #f4a460
(def seagreen "seagreen") ;; #2e8b57
(def seashell "seashell") ;; #fff5ee
(def sienna "sienna") ;; #a0522d
(def silver "silver") ;; #c0c0c0
(def skyblue "skyblue") ;; #87ceeb
(def slateblue "slateblue") ;; #6a5acd
(def slategray "slategray") ;; #708090
(def snow "snow") ;; #fffafa
(def springgreen "springgreen") ;; #00ff7f
(def steelblue "steelblue") ;; #4682b4
(def tan "tan") ;; #d2b48c
(def teal "teal") ;; #008080
(def thistle "thistle") ;; #d8bfd8
(def tomato "tomato") ;; #ff6347
(def turquoise "turquoise") ;; #40e0d0
(def violet "violet") ;; #ee82ee
(def wheat "wheat") ;; #f5deb3
(def white "white") ;; #ffffff
(def whitesmoke "whitesmoke") ;; #f5f5f5
(def yellow "yellow") ;; #ffff00
(def yellowgreen "yellowgreen") ;; #9acd32
